CREATE TABLE "parent" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL
);

CREATE TABLE "child" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR (80) UNIQUE NOT NULL,
	"number" VARCHAR (12) UNIQUE NOT NULL,
	"approved_id" INTEGER NOT NULL
);

CREATE TABLE "contacts" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR (80) UNIQUE NOT NULL,
	"number" VARCHAR (12) UNIQUE NOT NULL
);

CREATE TABLE "approved" (
	"id" SERIAL PRIMARY KEY,
	"name" VARCHAR (80) UNIQUE NOT NULL,
	"number" VARCHAR (12) UNIQUE NOT NULL
);

CREATE TABLE "non_approved" (
	"id" SERIAL PRIMARY KEY,
	"number" VARCHAR (12) UNIQUE NOT NULL,
	"time" TIMESTAMP NOT NULL,
	"child_id" INTEGER NOT NULL,
	"pending" BOOLEAN DEFAULT FALSE
);